### ISSUE TITLE
TypeError: Cannot destructure property 'header' of 'message' as it is undefined

### ISSUE THREAD

**Issue by bestmycode010** [solana-developers/solana-actions#31]
I got this error in Next.js - Transfer SOL example.

```
TypeError: Cannot destructure property 'header' of 'message' as it is undefined.
    at TransactionMessage.decompile (/var/task/node_modules/@solana/actions/node_modules/@solana/web3.js/lib/index.cjs.js:1985:7)
    at prepareVersionedTransaction (file:///var/task/node_modules/@solana/actions/lib/esm/createPostResponse.js:40:38)
    at createPostResponse (file:///var/task/node_modules/@solana/actions/lib/esm/createPostResponse.js:33:16)
    at handlePost (/var/task/frontend/.next/server/pages/api/claimsri.js:166:98)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handler (/var/task/frontend/.next/server/pages/api/claimsri.js:55:13)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:735:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:247:36)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:347:29)
    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:285:20)
    at async Server.<anonymous> (/var/task/frontend/___next_launcher.cjs:26:5)
    at async Server.<anonymous> (/opt/rust/nodejs.js:8:4243)
```

**Comment by nickfrosty** [comment]
where do you get this error?

can you share code snippets or a repo of what you are experiencing?

**Comment by nickfrosty** [comment]
This should now be resolved in the new version of the sdk. If you are still experiencing this issue, please reopen this issue or create a new one.
